server:
  port: 8080
  servlet:
    context-path: /mineria
  error:
      include-message: always




spring:
  security:
    basic:
      enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://opdhbb8zbtf2n9ii:m7adrnrba2dtkwka@gp96xszpzlqupw4k.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/t4by2jvmyflhgr7g
    username: opdhbb8zbtf2n9ii
    password: m7adrnrba2dtkwka
    hikari:
      maximum-pool-size: 5
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000

jpa:
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  show-sql: true

